"""
Combat assistance system Discord commands
Provides slash command interface for D&D combat management
"""
import discord
from discord.ext import commands
from discord import app_commands
from typing import Optional, List
from .combat_manager import CombatManager, CombatSession, CombatParticipant
from dice.advanced_roller import advanced_roller
import logging

logger = logging.getLogger(__name__)

class CombatCommands(commands.Cog):
    """Combat assistance command group"""
    
    def __init__(self, bot: commands.Bot):
        self.bot = bot
        self.combat_manager = CombatManager()
        self.dice_roller = advanced_roller
        
    async def cog_load(self):
        """Initialize when extension is loaded"""
        logger.info("Combat assistance command module loaded")
        
    async def cog_unload(self):
        """Cleanup when extension is unloaded"""
        logger.info("Combat assistance command module unloaded")
    

    
    def _create_combat_embed(self, combat: CombatSession, participants: List[CombatParticipant]) -> discord.Embed:
        """Create combat status embed message"""
        embed = discord.Embed(
            title=f"⚔️ Combat: {combat.name}",
            description=f"Round {combat.current_round}",
            color=discord.Color.red()
        )
        
        if participants:
            # Current turn character
            current_participant = participants[combat.current_turn] if combat.current_turn < len(participants) else None
            if current_participant:
                embed.add_field(
                    name="🎯 Current Turn",
                    value=f"{current_participant.type_icon} **{current_participant.name}**",
                    inline=False
                )
            
            # Initiative order
            initiative_list = []
            for i, participant in enumerate(participants):
                status = "👈" if i == combat.current_turn else "　"
                hp_bar = self._create_hp_bar(participant)
                initiative_list.append(
                    f"{status} {participant.status_icon} **{participant.name}** ({participant.initiative}) - {hp_bar}"
                )
            
            embed.add_field(
                name="📋 Initiative Order",
                value="\n".join(initiative_list) if initiative_list else "No participants",
                inline=False
            )
        else:
            embed.add_field(
                name="📋 Participants",
                value="No participants yet, use `/add` to add",
                inline=False
            )
        
        embed.set_footer(text=f"Combat ID: {combat.id} | DM permission required")
        return embed
    
    def _create_hp_bar(self, participant: CombatParticipant) -> str:
        """Create HP bar"""
        percentage = participant.hp_percentage
        bar_length = 10
        filled = int(bar_length * percentage / 100)
        empty = bar_length - filled
        
        bar = "█" * filled + "░" * empty
        return f"{participant.current_hp}/{participant.max_hp} HP |{bar}|"
    
    async def _check_dm_permission(self, interaction: discord.Interaction) -> bool:
        """Check DM permission and respond"""
        if not isinstance(interaction.user, discord.Member):
            await interaction.response.send_message("❌ This command can only be used in a server", ephemeral=True)
            return False
            
        if not await self.combat_manager.is_dm(interaction.user):
            await interaction.response.send_message("❌ Only DMs can use this command", ephemeral=True)
            return False
            
        return True
    
    # ===== Combat Management Commands =====
    
    @app_commands.command(name="cs", description="Start a new combat session")
    @app_commands.describe(name="Combat name (optional, auto-generated by default)")
    async def start_combat(self, interaction: discord.Interaction, name: Optional[str] = None):
        """Start new combat"""
        if not await self._check_dm_permission(interaction):
            return
        
        # Check if there's already an active combat
        existing = await self.combat_manager.get_active_combat(
            interaction.guild_id, interaction.channel_id
        )
        if existing:
            embed = discord.Embed(
                title="⚠️ Active Combat Exists",
                description=f"Combat `{existing.name}` is already in progress in this channel\nUse `/ce` to end the current combat",
                color=discord.Color.orange()
            )
            await interaction.response.send_message(embed=embed, ephemeral=True)
            return
        
        # Generate default combat name
        if not name:
            import datetime
            timestamp = datetime.datetime.now().strftime("%m-%d %H:%M")
            name = f"Combat {timestamp}"
        
        # Create new combat
        combat = await self.combat_manager.start_combat(
            interaction.guild_id, interaction.channel_id, interaction.user.id, name
        )
        
        if combat:
            embed = discord.Embed(
                title="⚔️ Combat Started!",
                description=f"Combat `{name}` has begun",
                color=discord.Color.green()
            )
            embed.add_field(
                name="📝 Next Steps",
                value="Use `/add` to add participants\nUse `/st` to view combat status",
                inline=False
            )
            embed.set_footer(text=f"Combat ID: {combat.id}")
            await interaction.response.send_message(embed=embed)
            
            logger.info(f"User {interaction.user} started combat in channel {interaction.channel_id}: {name}")
        else:
            await interaction.response.send_message("❌ Failed to create combat, please try again later", ephemeral=True)
    
    @app_commands.command(name="ce", description="End the current combat")
    async def end_combat(self, interaction: discord.Interaction):
        """End combat"""
        if not await self._check_dm_permission(interaction):
            return
        
        combat = await self.combat_manager.get_active_combat(
            interaction.guild_id, interaction.channel_id
        )
        
        if not combat:
            await interaction.response.send_message("❌ No active combat in this channel", ephemeral=True)
            return
        
        success = await self.combat_manager.end_combat(combat.id)
        
        if success:
            embed = discord.Embed(
                title="🏁 Combat Ended",
                description=f"Combat `{combat.name}` has ended",
                color=discord.Color.blue()
            )
            embed.add_field(
                name="📊 Combat Statistics",
                value=f"Total rounds: {combat.current_round}\nParticipants: {len(combat.participants)}",
                inline=False
            )
            embed.add_field(
                name="📚 View Logs",
                value="Use `/log` to view detailed combat records",
                inline=False
            )
            await interaction.response.send_message(embed=embed)
            
            logger.info(f"User {interaction.user} ended combat: {combat.name}")
        else:
            await interaction.response.send_message("❌ Failed to end combat, please try again later", ephemeral=True)
    
    @app_commands.command(name="st", description="View current combat status")
    async def st(self, interaction: discord.Interaction):
        """View combat status"""
        combat = await self.combat_manager.get_active_combat(
            interaction.guild_id, interaction.channel_id
        )
        
        if not combat:
            embed = discord.Embed(
                title="ℹ️ No Active Combat",
                description="No combat in progress in this channel\nUse `/cs` to start a new combat",
                color=discord.Color.blue()
            )
            await interaction.response.send_message(embed=embed, ephemeral=True)
            return
        
        participants = await self.combat_manager.get_participants(combat.id)
        embed = self._create_combat_embed(combat, participants)
        
        await interaction.response.send_message(embed=embed)
    
    # ===== Participant Management Commands =====
    
    @app_commands.command(name="add", description="Add a combat participant")
    @app_commands.describe(
        name="Character name",
        max_hp="Maximum hit points",
        initiative="Initiative value",
        ac="Armor class (optional)",
        is_npc="Is this an NPC? (optional)"
    )
    async def add(
        self, interaction: discord.Interaction, 
        name: str, max_hp: int, initiative: int,
        ac: Optional[int] = 10, is_npc: Optional[bool] = False
    ):
        """Add participant"""
        if not await self._check_dm_permission(interaction):
            return
        
        combat = await self.combat_manager.get_active_combat(
            interaction.guild_id, interaction.channel_id
        )
        
        if not combat:
            await interaction.response.send_message("❌ No active combat in this channel", ephemeral=True)
            return
        
        # Validate values
        if max_hp <= 0:
            await interaction.response.send_message("❌ Maximum HP must be greater than 0", ephemeral=True)
            return
        
        if len(name) > 50:
            await interaction.response.send_message("❌ Character name too long (max 50 characters)", ephemeral=True)
            return
        
        participant = await self.combat_manager.add_participant(
            combat.id, name, max_hp, initiative, ac, is_npc
        )
        
        if participant:
            embed = discord.Embed(
                title="✅ Participant Added",
                description=f"{participant.type_icon} **{name}** joined the combat!",
                color=discord.Color.green()
            )
            embed.add_field(name="Initiative", value=str(initiative), inline=True)
            embed.add_field(name="Hit Points", value=f"{max_hp}/{max_hp}", inline=True)
            embed.add_field(name="Armor Class", value=str(ac), inline=True)
            
            await interaction.response.send_message(embed=embed)
            
            logger.info(f"User {interaction.user} added participant: {name}")
        else:
            await interaction.response.send_message("❌ Failed to add participant, name may already exist", ephemeral=True)
    
    @app_commands.command(name="rm", description="Remove a combat participant")
    @app_commands.describe(name="Character name to remove")
    async def rm(self, interaction: discord.Interaction, name: str):
        """Remove participant"""
        if not await self._check_dm_permission(interaction):
            return
        
        combat = await self.combat_manager.get_active_combat(
            interaction.guild_id, interaction.channel_id
        )
        
        if not combat:
            await interaction.response.send_message("❌ No active combat in this channel", ephemeral=True)
            return
        
        success = await self.combat_manager.remove_participant(combat.id, name)
        
        if success:
            embed = discord.Embed(
                title="✅ Participant Removed",
                description=f"**{name}** has left the combat",
                color=discord.Color.blue()
            )
            await interaction.response.send_message(embed=embed)
            
            logger.info(f"User {interaction.user} removed participant: {name}")
        else:
            await interaction.response.send_message("❌ Failed to remove participant, character may not exist", ephemeral=True)
    
    # ===== Turn Management Commands =====
    
    @app_commands.command(name="next", description="Advance to the next turn")
    async def next(self, interaction: discord.Interaction):
        """Next turn"""
        if not await self._check_dm_permission(interaction):
            return
        
        combat = await self.combat_manager.get_active_combat(
            interaction.guild_id, interaction.channel_id
        )
        
        if not combat:
            await interaction.response.send_message("❌ No active combat in this channel", ephemeral=True)
            return
        
        current_participant = await self.combat_manager.next_turn(combat.id)
        
        if current_participant:
            embed = discord.Embed(
                title="🔄 Turn Changed",
                description=f"It's now **{current_participant.name}**'s turn",
                color=discord.Color.gold()
            )
            
            # Refresh combat status after update
            updated_combat = await self.combat_manager.get_active_combat(
                interaction.guild_id, interaction.channel_id
            )
            if updated_combat:
                embed.add_field(
                    name="⏰ Current Status",
                    value=f"Round {updated_combat.current_round}",
                    inline=True
                )
            
            hp_bar = self._create_hp_bar(current_participant)
            embed.add_field(
                name="💖 Hit Points",
                value=hp_bar,
                inline=False
            )
            
            await interaction.response.send_message(embed=embed)
            
            logger.info(f"Combat turn advanced to: {current_participant.name}")
        else:
            await interaction.response.send_message("❌ Failed to advance turn, check if there are participants", ephemeral=True)
    
    # ===== HP Management Commands =====
    
    @app_commands.command(name="dmg", description="Deal damage to a character")
    @app_commands.describe(
        target="Target character name",
        expression="Damage expression (e.g., 2d6+3) or fixed value",
        attacker="Attacker name (optional)"
    )
    async def apply_dmg(
        self, interaction: discord.Interaction, 
        target: str, expression: str, attacker: Optional[str] = None
    ):
        """Deal damage"""
        if not await self._check_dm_permission(interaction):
            return
        
        combat = await self.combat_manager.get_active_combat(
            interaction.guild_id, interaction.channel_id
        )
        
        if not combat:
            await interaction.response.send_message("❌ No active combat in this channel", ephemeral=True)
            return
        
        # If no attacker specified, use current turn character name
        if attacker is None:
            participants = await self.combat_manager.get_participants(combat.id)
            if participants and combat.current_turn < len(participants):
                attacker = participants[combat.current_turn].name
            else:
                attacker = interaction.user.display_name
        
        # Parse damage value
        try:
            # Try to parse as number directly
            if expression.isdigit():
                dmg = int(expression)
                dice_result = f"Fixed damage: {dmg}"
            else:
                # Use dice system
                result = await self.dice_roller.roll(
                    expression, interaction.user.id, interaction.guild_id or 0, interaction.channel_id or 0
                )
                dmg = result.final_value
                dice_result = f"{expression}: {result.final_value}"
        except Exception as e:
            await interaction.response.send_message(f"❌ Invalid damage expression: {expression}", ephemeral=True)
            return
        
        if dmg < 0:
            await interaction.response.send_message("❌ Damage cannot be negative", ephemeral=True)
            return
        
        participant = await self.combat_manager.apply_damage(
            combat.id, target, dmg, attacker, expression, dice_result
        )
        
        if participant:
            embed = discord.Embed(
                title="💥 Damage Applied",
                description=f"**{attacker}** → **{target}**",
                color=discord.Color.red()
            )
            embed.add_field(name="🎲 Roll Result", value=dice_result, inline=False)
            embed.add_field(name="💔 Damage", value=f"{dmg} points", inline=True)
            
            hp_bar = self._create_hp_bar(participant)
            embed.add_field(name="💖 Remaining HP", value=hp_bar, inline=False)
            
            if participant.current_hp <= 0:
                embed.add_field(name="💀 Status", value=f"**{target}** is down!", inline=False)
            
            await interaction.response.send_message(embed=embed)
            
            logger.info(f"Dealt {dmg} damage to {target}")
        else:
            await interaction.response.send_message(f"❌ Character not found: {target}", ephemeral=True)
    
    @app_commands.command(name="heal", description="Heal a character")
    @app_commands.describe(
        target="Target character name",
        expression="Healing expression (e.g., 1d8+2) or fixed value",
        healer="Healer name (optional)"
    )
    async def apply_healing(
        self, interaction: discord.Interaction,
        target: str, expression: str, healer: Optional[str] = None
    ):
        """Apply healing"""
        if not await self._check_dm_permission(interaction):
            return
        
        combat = await self.combat_manager.get_active_combat(
            interaction.guild_id, interaction.channel_id
        )
        
        if not combat:
            await interaction.response.send_message("❌ No active combat in this channel", ephemeral=True)
            return
        
        # If no healer specified, use current turn character name
        if healer is None:
            participants = await self.combat_manager.get_participants(combat.id)
            if participants and combat.current_turn < len(participants):
                healer = participants[combat.current_turn].name
            else:
                healer = interaction.user.display_name
        
        # Parse healing value
        try:
            if expression.isdigit():
                healing = int(expression)
                dice_result = f"Fixed healing: {healing}"
            else:
                result = await self.dice_roller.roll(
                    expression, interaction.user.id, interaction.guild_id or 0, interaction.channel_id or 0
                )
                healing = result.final_value
                dice_result = f"{expression}: {result.final_value}"
        except Exception as e:
            await interaction.response.send_message(f"❌ Invalid healing expression: {expression}", ephemeral=True)
            return
        
        if healing < 0:
            await interaction.response.send_message("❌ Healing cannot be negative", ephemeral=True)
            return
        
        participant = await self.combat_manager.apply_healing(
            combat.id, target, healing, healer, expression, dice_result
        )
        
        if participant:
            embed = discord.Embed(
                title="✨ Healing Applied",
                description=f"**{healer}** → **{target}**",
                color=discord.Color.green()
            )
            embed.add_field(name="🎲 Roll Result", value=dice_result, inline=False)
            embed.add_field(name="💚 Healing", value=f"{healing} points", inline=True)
            
            hp_bar = self._create_hp_bar(participant)
            embed.add_field(name="💖 Current HP", value=hp_bar, inline=False)
            
            await interaction.response.send_message(embed=embed)
            
            logger.info(f"Healed {target} for {healing} HP")
        else:
            await interaction.response.send_message(f"❌ Character not found: {target}", ephemeral=True)

async def setup(bot: commands.Bot):
    """Load combat commands extension"""
    await bot.add_cog(CombatCommands(bot)) 